### ISSUE TITLE
Reserved memory causes undefined behavior unless jumped over

### ISSUE THREAD

**Issue by The-furf-of-July** [ScottPiersall/SICVM#26]
If you try to use resb, resw, word, or byte anywhere that the program counter reaches, it leads to unintentional behavior and sometimes stalls the machine. 

My guess as to why this happens is it tries to run the contents of the reserved memory as if they were opcodes, when it should instead get skipped over.

For now, this is avoidable by placing all reserved memory in places that are bypassed with J, JGT, JEQ, or JLT.

**Comment by SubstituteR** [comment]
I don't think this is an issue directly with the VM.  The Assembler could possibly relocate definitions and place them ahead of all operations, but that's not the Assembler's job either.
